### ISSUE TITLE
Migrations are broken

### ISSUE THREAD

**Issue by vladarefiev** [timelesslounge/timelessis#50]
I'm trying to run `python manage.py db upgrade` on empty db and get these:

```
(venv) MBP-Vlad:timelessis vladarefev$ python manage.py db upgrade
/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 503a67df3f7f, empty message
INFO  [alembic.runtime.migration] Running upgrade 503a67df3f7f -> be62103a5fd6, empty message
INFO  [alembic.runtime.migration] Running upgrade be62103a5fd6 -> 4e1a909ab513, empty message
INFO  [alembic.runtime.migration] Running upgrade 4e1a909ab513 -> 4d7589fae495, empty message
INFO  [alembic.runtime.migration] Running upgrade 4d7589fae495 -> 79f280c6c1f4, empty message
INFO  [alembic.runtime.migration] Running upgrade 79f280c6c1f4 -> 0d17ec999973, empty message
ERROR [alembic.env] (psycopg2.ProgrammingError) column "address" of relation "companies" already exists
 [SQL: 'ALTER TABLE companies ADD COLUMN address VARCHAR'] (Background on this error at: http://sqlalche.me/e/f405)
Traceback (most recent call last):
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
    cursor, statement, parameters, context
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column "address" of relation "companies" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    MANAGER.run()
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 156, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 91, in <module>
    run_migrations_online()
  File "migrations/env.py", line 84, in run_migrations_online
    raise exception
  File "migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
    step.migration_fn(**kw)
  File "/Users/vladarefev/timelessis/migrations/versions/0d17ec999973_.py", line 21, in upgrade
    op.add_column('companies', sa.Column('address', sa.String(), nullable=True))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/operations/ops.py", line 1904, in add_column
    return operations.invoke(op)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 131, in add_column
    operations.impl.add_column(table_name, column, schema=schema)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/ddl/impl.py", line 230, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 974, in execute
    return meth(self, multiparams, params)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1036, in _execute_ddl
    compiled,
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1234, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
    cursor, statement, parameters, context
  File "/Users/vladarefev/timelessis/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "address" of relation "companies" already exists
 [SQL: 'ALTER TABLE companies ADD COLUMN address VARCHAR'] (Background on this error at: http://sqlalche.me/e/f405)
(venv) MBP-Vlad:timelessis vladarefev$ 

```

**Comment by 0pdd** [comment]
@vladarefiev the only puzzle [#98](https://github.com/timelesslounge/timelessis/issues/98) is solved here.
